./boot.sh netpay-db-service4
./boot.sh netpay-db-bills4
sleep 30
./boot.sh netpay-route-server4
./boot.sh netpay-risk-control4
./boot.sh netpay-wxpay-open4
./boot.sh netpay-alipay-open4
./boot.sh netpay-web-manage4
./boot.sh netpay-gateway4
#./boot.sh netpay-jobs4
./boot.sh netpay-postman4
./boot.sh netpay-bills4
./boot.sh netpay-portal4
./boot.sh netpay-manager4
./boot.sh netpay-http-post4
./boot.sh netpay-public-service4
./boot.sh netpay-mer-portal4
